# https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-python#publishing-to-pypi

name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo $HOME/.local/bin >> $GITHUB_PATH
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
          cache: poetry
      - run: poetry install
      - run: poetry run pytest test.py
      - run: poetry build
      - uses: pypa/gh-action-pypi-publish@release/v1
